Feature/wmt 39/async worker
ministryofjustice/noms-wmt-alpha pull request #13
Opened 2017-03-08 18:23 UTC by tswann

This technical spike covers:

- Demonstration of async worker for executing business rules
- Generic task queue mechanism for scheduling work submitted by different agents (e.g. the web app)
- Using NPM modules as a means of encapsulating business rules/calculations
- Bunyan for logging

2017-03-15 15:14 UTC, andrew-js-wright requested changes
Just one small comment, nice approach otherwise.

2017-03-15 15:14 UTC, andrew-js-wright commented on wmt-worker/app/services/data/get-pending-tasks-and-mark-in-progress.js
> +      if (results) {
If there are no tasks returned this will be an empty array, which will be truthy. Therefore this should probably be testing array length instead.

2017-03-16 13:10 UTC, tswann commented
@andrew-js-wright - comments applied, thanks! TS

2017-03-16 13:40 UTC, andrew-js-wright approved these changes

2017-03-16 13:41 UTC, merged